import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { getOBBOauthUrl } from "./helper";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Onboardbase OAuth Sample Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 style={{ padding: "1rem" }} className={inter.className}>
          Onboardbase OAuth Sample Project
        </h1>
        <button style={{ padding: "1rem" }}>
          <a href={getOBBOauthUrl(`{ "hi": "there" }`)}>
            <p className={inter.className}>Authenticate with Onboardbase</p>
          </a>
        </button>
      </main>
    </>
  );
}
