import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { getOBBOauthUrl } from "../utils/helper";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Onboardbase OAuth Sample Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 style={{ padding: "1rem" }} className={inter.className}>
          Onboardbase OAuth Sample Project
        </h1>
        <Link
          href={getOBBOauthUrl(`{ "hi": "there" }`)}
          className="border rounded hover:bg-slate-500"
        >
          <button className="p-2">Authenticate with Onboardbase</button>
        </Link>
      </main>
    </>
  );
}
